# GenoRing docker compose file
#
# Run with "docker compose up" or "docker compose up -d"
# Stop with "docker compose down"
#
# Access through "http://localhost:8080"
#

version: '3.4'

services:

  genoring:
    image: guignon/genoring:alpha1
    env_file:
      - 'genoring.env'
    volumes:
      - genoring-drupal-volume:/opt/drupal
      - ./volumes/drupal/modules:/opt/drupal/web/modules
      - ./volumes/drupal/profiles:/opt/drupal/web/profiles
      - ./volumes/drupal/themes:/opt/drupal/web/themes
      - ./volumes/drupal/vendor:/opt/drupal/vendor
      - ./volumes/drupal/config:/opt/drupal/config
      - ./volumes/drupal/private:/opt/drupal/private
      - ./volumes/drupal/sites/default:/opt/drupal/web/sites/default
      - ./volumes/drupal/drupal:/opt/drupal/exposed
      - ./volumes/php:/opt/drupal/php
    depends_on:
      - db
    restart: always

  proxy:
    image: nginx
    ports:
      - 8080:80
    env_file:
      - 'genoring.env'
    volumes:
      - type: bind
        source: ./proxy/genoring-fpm.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - genoring-drupal-volume:/opt/drupal
    depends_on:
      - genoring
    restart: always

  db:
    image: postgres:15
    env_file:
      - 'genoring.env'
    volumes:
      - ./volumes/db/pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  genoring-drupal-volume:
