# GenoRing docker compose file
#
# Run with "docker compose up" or "docker compose up -d"
# Stop with "docker compose down"
#
# Access through "http://localhost:8080"
#

version: '3.4'

services:

  genoring:
    image: guignon/genoring:alpha2
    env_file:
      - './env/genoring.env'
    volumes:
      - genoring-drupal-volume:/opt/drupal
      - ./volumes/drupal/modules:/opt/drupal/web/modules
      - ./volumes/drupal/profiles:/opt/drupal/web/profiles
      - ./volumes/drupal/themes:/opt/drupal/web/themes
      - ./volumes/drupal/vendor:/opt/drupal/vendor
      - ./volumes/drupal/config:/opt/drupal/config
      - ./volumes/drupal/private:/opt/drupal/private
      - ./volumes/drupal/sites/default:/opt/drupal/web/sites/default
      - ./volumes/drupal/drupal:/opt/drupal/exposed
      - ./volumes/php:/opt/drupal/php
    depends_on:
      - db
    restart: always

  proxy:
    image: nginx
    env_file:
      - './env/nginx.env'
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ./proxy/genoring-fpm.conf
        target: /etc/nginx/templates/default.conf.template
      - genoring-drupal-volume:/opt/drupal
    depends_on:
      - genoring
    restart: always

  db:
    image: postgres:15
    env_file:
      - './env/genoring.env'
    volumes:
      - ./volumes/db/pgdata:/var/lib/postgresql/data
    restart: always

  gigwa_service:
    profiles: ["gigwa"]
    image: guilhemsempere/gigwa:2.6.2-beta
    env_file:
      - './env/gigwa.env'
    ports:
      - 8123:8080
    volumes:
      - ./volumes/gigwa:/usr/local/tomcat/config
    depends_on:
      - mongo
    restart: always

  mongo:
    profiles: ["gigwa"]
    image: mongo:4.2.24
    env_file:
      - './env/gigwa.env'
    command: --profile 0 --slowms 60000 --storageEngine wiredTiger --wiredTigerCollectionBlockCompressor=zstd --directoryperdb --quiet
    ports:
      - 59393:27017 # You may amend the external port only (left hand side), which must match the above MONGO_PORT
    volumes:
      - ./volumes/mongo:/data/db
    restart: always

volumes:
  genoring-drupal-volume:
