#!/usr/bin/env perl

use strict;
use warnings;
use utf8;
use FindBin;
use lib "$FindBin::Bin";
use Genoring::GenoringTool;

my $program = new Genoring::GenoringTool('busco');
$program->run();
print $program->getResponse();
