#!/usr/bin/env perl

package Genoring::faidx;

use strict;
use warnings;
use utf8;
use FindBin;
use lib "$FindBin::Bin";
use Genoring::GenoringTool;

use base qw(Genoring::GenoringTool);

sub getProgram
{
  return 'samtools faidx';
}

sub getParameters
{
  my ($self) = @_;

  # Get parameters.
  my $fasta_file = $self->query->param('fasta') || '';
  my $output_file = $self->query->param('output') || '';

  # Check for parameter error.
  my $error = $self->query->cgi_error;
  if ($error) {
    # Request not processed.
    $self->data->{'error'} = $error;
    return;
  }

  # Missing FASTA.
  if (!$fasta_file) {
    $self->data->{'error'} = '400 Missing FASTA file path';
    return;
  }

  my $parameters = $fasta_file;
  if ($output_file) {
    $parameters .= ' -o ' . $output_file;
    $self->data->{'output_fai'} = $output_file;
  }
  else {
    $self->data->{'output_fai'} = $fasta_file . '.fai';
  }
  return $parameters;
}

my $program = new Genoring::faidx('faidx');
$program->run();
print $program->getResponse();
